package by.epamtc.restaurant.controller.command;

public enum ParameterName {

	LOGIN,
	REGISTRATION,
	LOGOUT,
	UPDATE_USER_DATA,
	
	GO_TO_WELCOME_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_LOGIN_PAGE,
	GO_TO_ERROR_PAGE,
	GO_TO_MENU_PAGE,
	GO_TO_STOCK_PAGE,
	GO_TO_ABOUT_US_PAGE,
	GO_TO_CONTACT_PAGE,
	GO_TO_PERSONAL_ACCOUNT_PAGE,
	GO_TO_UPDATE_USER_DATA_PAGE,
	GO_TO_ORDER_PAGE,
	GO_TO_GRATITUDE_PAGE,
	GO_TO_USER_ORDER_PAGE,
	GO_TO_ADMIN_PAGE,
	GO_TO_UNCONFIRMED_ORDER_PAGE,
	GO_TO_CONFIRMED_ORDER_PAGE,
	GO_TO_CLIENTS_PAGE,
	GO_TO_EMPLOYEES_PAGE,
	GO_TO_PAYMENTS_PAGE,
	
	ADD_DISH_TO_ORDER,
	ADD_DRINK_TO_ORDER,
	ADD_DESERT_TO_ORDER,
	PLACE_ORDER,
	
	CHANGE_ORDER_STATUS,
	APPOINT_AN_ADMINISTRATOR,
	APPOINT_AN_USER,
}
