package by.epamtc.restaurant.controller.command;

public enum ParameterName {

	LOGIN,
	REGISTRATION,
	LOGOUT,
	UPDATE_USER_DATA,
	GO_TO_WELCOME_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_LOGIN_PAGE,
	GO_TO_ERROR_PAGE,
	GO_TO_MENU_PAGE,
	GO_TO_STOCK_PAGE,
	GO_TO_ABOUT_US_PAGE,
	GO_TO_CONTACT_PAGE,
	GO_TO_PERSONAL_ACCOUNT_PAGE,
	GO_TO_UPDATE_USER_DATA_PAGE
}
